### ISSUE TITLE
icons resetting

### ISSUE THREAD

**Issue by brightersun99** [window-maker/wmaker#1] opened 2020-09-07 19:46 UTC
I am running the latest windowmaker. 

I have some icons saved to my dock/clip, for launching things. I have set their icons to custom icons

And it works until I launch the program, then it reverts back to its original icon.  Right clicking and editing it shows the path is still set to my custom icon, I can change it and it will still revert again until I do something with that program. 

Seems this has been a bug since around 2004, fix it please?

**Comment by gryf** [comment] 2020-09-09 19:25
There are two different things - icons for docked things *before launch* and the one programs owns.

So I assume, you've been dragged xterm (let's make it an example) to the dock, and there change the icon using this option in docked item settings:

![Untitled](https://user-images.githubusercontent.com/264785/92641898-b6fec480-f2df-11ea-8e14-4e0c48c8a75f.png)
and the icon on the dock would for example look like:
![Untitled2](https://user-images.githubusercontent.com/264785/92642456-7fdce300-f2e0-11ea-8b3c-3cda837c4a1b.png)
but after double click on it you will end up with Xterm icon replacing the one specified previously:
![3](https://user-images.githubusercontent.com/264785/92642399-6b004f80-f2e0-11ea-95bf-ebfcd3fa4ae0.png)
and well. After killing/closing xterm, your defined icon on dock should appear again :)

And that's perfectly fine, because this option is for specifying an dock icon for windowless/iconless actions (like - launching some bash scripts, reload services etc). But you are probably launch a program which have a window and defined icon. To achieve what you want (aligned icon between program and icon on What are you looking for is:

- run the xterm (we are still using xterm as an example)
- right click on the xterm titlebar to pop up window menu
- select attributes
- from option menu on top select "icon and initial workspace"
- browse for desired icon
- don't forget to tick checkbox "ignore client supplied icon"
- apply + save
- drag from clip to dock (or alternatively right click on icon which is attracted to clip, select "keep icon")

And it should work :)

**Comment by brightersun99** [comment] 2020-09-10 06:42
Thank you, you are awesome. I would have never found such an estoeric fix without your assistance, Thanks again.

**Comment by gryf** [comment] 2020-09-10 15:28
Perhaps we should adapt this to the docs (as a FAQ/Note or whatever).

**Comment by crmafra** [comment] 2020-09-10 16:24
On Thu, 10 Sep 2020 at  8:28:40 -0700, Roman Dobosz wrote:
> Perhaps we should adapt this to the docs (as a FAQ/Note or whatever).

Good idea. Would you like to write a patch to the window maker
homepage?

https://github.com/window-maker/window-maker.github.io

**Comment by gryf** [comment] 2020-09-11 05:59
@crmafra I've filled an issue for it https://github.com/window-maker/window-maker.github.io/issues/11 just to not forget :)

**Comment by brightersun99** [comment] 2020-09-13 07:43
> There are two different things - icons for docked things _before launch_ and the one programs owns.
> 
> So I assume, you've been dragged xterm (let's make it an example) to the dock, and there change the icon using this option in docked item settings:
> 
> ![Untitled](https://user-images.githubusercontent.com/264785/92641898-b6fec480-f2df-11ea-8e14-4e0c48c8a75f.png)
> and the icon on the dock would for example look like:
> ![Untitled2](https://user-images.githubusercontent.com/264785/92642456-7fdce300-f2e0-11ea-8b3c-3cda837c4a1b.png)
> but after double click on it you will end up with Xterm icon replacing the one specified previously:
> ![3](https://user-images.githubusercontent.com/264785/92642399-6b004f80-f2e0-11ea-95bf-ebfcd3fa4ae0.png)
> and well. After killing/closing xterm, your defined icon on dock should appear again :)
> 
> And that's perfectly fine, because this option is for specifying an dock icon for windowless/iconless actions (like - launching some bash scripts, reload services etc). But you are probably launch a program which have a window and defined icon. To achieve what you want (aligned icon between program and icon on dock), here are the steps:
> 
> * run the xterm (we are still using xterm as an example)
> * right click on the xterm titlebar to pop up window menu
> * select attributes
> * from option menu on top select "icon and initial workspace"
> * browse for desired icon
> * don't forget to tick checkbox "ignore client supplied icon"
> * apply + save
> * drag from clip to dock (or alternatively right click on icon which is attracted to clip, select "keep icon")
> 
> And it should work :)

It seems my issue, while less frequent still exists, more or less for some programs. 

For example, my terminal now behaves most of the time, but still rarely it reverts to its old icon. 
Seamonkey on the other hand is very aggressive about keeping its old icon and the fix does not work for it at all. 
Do you have any other ideas? I was thinking I could write a wrapper that launched their respective programs with ONLY the icon I want

**Comment by gryf** [comment] 2020-09-13 12:04
The only thing I can think of is that it is connected with saving session. Do you use saving session for wmaker?
Do you have any other program, which behave that way as seamonky?
And finally: perhaps starting up wmaker with fresh configuration might help to reveal the root cause of the issue.

**Comment by brightersun99** [comment] 2020-09-20 09:14
Hi, been messing with this. 
I did a fresh slate. new install of my distro and everything, so the icon for seamonkey couldn't have been cached. 
Just to be safe, I replaced all variants of seamonkeys original icon with my own. I started seamonkey, added it to my dock and applied ignore client icon. 
But while its running it aggressivly maintains its own icon, I don't know where it gets it from! I thought I deleted or overwrote every distance of them and evne made them write protected..
I start with a fresh session each time, I do not have any session saving but to debug that anyways Ive been doing fresh configs and wiping all saved states when testing things.

**Comment by gryf** [comment] 2020-09-22 10:22
Perhaps this is strictly connected with Seamonkey, which might happen to manage its own icon by itself. Do you observe such a behavior on other programs as well? Can you provide the names?

**Comment by brightersun99** [comment] 2020-09-24 12:53
xpaint is another example.

**Comment by gryf** [comment] 2020-09-25 05:10
I have tested steps described above with xpaint-2.10.2 and it's seems to work. Icon firmly stays changed.

**Comment by gryf** [comment] 2021-03-17 10:15
Didn't hear from @brightersun99 about this issue for couple of months now. I guess we can close it, otherwise it could be reopened. Note, that documentation issue is under another repo.

**Closed by gryf** 2021-03-17 10:15 UTC
Labels: documentation
